select
    salesorderid as sales_order_id,
    customerid as customer_id,
    creditcardid as credit_card_id,
    billtoaddressid as bill_to_address_id,
    shiptoaddressid as ship_to_address_id,
    shipmethodid as ship_method_id,
    salespersonid as salesperson_id,
    territoryid as territory_id,
    status as order_status,
    cast(orderdate as date) as order_date,
    duedate as due_date,
    shipdate as ship_date,
    onlineorderflag as online_order_flag,
    subtotal,
    taxamt as tax_amt,
    freight,
    totaldue as total_due,
    accountnumber as account_number,
    creditcardapprovalcode as credit_card_approval_code,
    currencyrateid as currency_rate_id,
    revisionnumber as revision_number,
    rowguid as row_guid,
    modifieddate as modified_date
from {{ ref('salesorderheader') }}
